name: resippy
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - pdal
  - pip
  - psutil
  - pyproj
  - python
  - python-pdal
  - scikit-image
  - scikit-learn
  - shapely
  - pip:
    - colorutils
    - imageio
    - numpy<1.16.0
    - opencv-python
    - pint==0.9
    - pyexiftool
    - pysolar
    - scipy
    - seaborn
