name: resippy
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal=2.4.1
  - pdal=1.9.1
  - pip=19.1.1
  - psutil=5.6.3
  - pyproj=2.1.3
  - python=3.7.3
  - python-pdal=2.1.8
  - pip:
    - scikit-learn
    - git+https://github.com/BeamIO-Inc/resippy.git
