name: resippy
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - pdal
  - pip
  - psutil
  - pyproj
  - python
  - python-pdal
  - scikit-learn
  - pip:
    - opencv-python
    - pyexiftool
    - pysolar
    - git+https://github.com/BeamIO-Inc/resippy.git
    - git+https://github.com/BeamIO-Inc/algorithm_toolkit  
