name: resippy
channels:
  - defaults
  - conda-forge
dependencies:
  - cython=0.29.12
  - gdal=2.2.4
  - openssl=1.0.2s
  - pdal=1.7.1
  - pip=19.1.1
  - pyproj=1.9.5.1
  - python=3.6.6
  - python-pdal=2.0.0
  - scikit-learn=0.21.2
  - pip:
    - git+https://github.com/BeamIO-Inc/resippy.git
