name: resippy
channels:
  - defaults
  - conda-forge
dependencies:
  - cython
  - gdal
  - openssl
  - pdal
  - pip
  - pyproj
  - python
  - python-pdal
  - scikit-learn
  - pip:
    - git+https://github.com/BeamIO-Inc/resippy.git
