name: resippy
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - cython
  - pdal
  - pip
  - psutil
  - pyproj
  - python
  - python-pdal
  - scikit-image
  - scikit-learn
  - shapely
  - exifread
  - pip:
    - colorutils
    - imageio
    - numpy
    - opencv-python
    - pint
    - exifread
    - scipy
    - seaborn
    - utm
